name: CI

on:
  push:
    branches: [ main, development, release ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"] 

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Run tests
      run: python test.py
    - name: Install Sphinx
      run: pip install sphinx sphinx-rtd-theme
    - name: Build documentation
      run: |
        make html
    - name: Upload documentation
      uses: actions/upload-artifact@v3
      with:
        name: documentation
        path: ./build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/html
        publish_branch: gh-pages